"""
File       : conf_handler.py
Author     : Fluffy Flower (Martin Wylde)
Contact    :
    Email   - martincw1989@gmail.com
    Telegram- @FluffyFlower
    Discord - fluffy_flower
Date       : 23/01/2025
Version    : 1.0.0
Description: Configuration handler for saving settings to dxvk.conf and vkBasalt.conf files.
"""

# ------------------------------------------------------ #
#                                                        #
# ██████                                                 #
#   ██    ██  ██  ████    ██████    ████    ██      ████ #
#   ██    ██████  ██  ██  ██  ██  ██      ██████    ██   #
#   ██    ██████  ██████  ██  ██  ██        ██      ██   #
# ██████  ██  ██  ██      ██████  ██        ████  ████   #
#                                                        #
# ------------------------------------------------------ #
import os


# ------------------------------------------------------------------------------------------------ #
#                                                                                                  #
# ██████                    ████            ██  ██                      ██                         #
# ██  ██  ██████  ██████    ██              ██  ██    ████  ██████      ██  ██        ████    ████ #
# ██      ██  ██  ██  ██  ██████            ██████  ██  ██  ██  ██    ████  ██      ██  ██  ██     #
# ██  ██  ██  ██  ██  ██    ██              ██  ██  ██  ██  ██  ██  ██  ██  ██      ████    ██     #
# ██████  ██████  ██  ██    ██              ██  ██  ██████  ██  ██  ██████  ██████    ████  ██     #
#                                                                                                  #
# ------------------------------------------------------------------------------------------------ #


class AppConfHandler:
    """
    Class for handling dxvk and vkBasalt configuration files.
    """

    def __init__(self, dxvk_config="dxvk.conf", vkbasalt_config="vkBasalt.conf"):
        self._dxvk_config: str = dxvk_config
        self._vkbasalt_config: str = vkbasalt_config

    def save_conf_vkbasalt(self,
                           app_path_in: str,
                           settings_list: list) -> None:
        """
        Saves vkBasalt configuration based on provided settings from dropdowns in settings_panel.py.

        Args:
            app_path_in (str): Path to the application directory.
            settings_list (list): List of settings values from the GUI.
        
        Returns:
            None.

        Raises:
            None.
        
        Example:
            Default usage:
                .. code-block:: python
                >>> conf_handler = AppConfHandler()
                >>> conf_handler.save_conf_vkbasalt("/path/to/app", settings_list)
        """
        # Unpack settings list
        gui_data: list = settings_list

        fxaa_enable: bool = gui_data[0]
        fxaa_quality_subpixel: str = gui_data[1]
        fxaa_quality_edge: str = gui_data[2]
        fxaa_edge_threshold: str = gui_data[3]
        smaa_enable: bool = gui_data[4]
        smaa_edge_detection: str = gui_data[5]
        smaa_threshold: str = gui_data[6]
        smaa_search_steps: str = gui_data[7]
        smaa_search_steps_diagonal: str = gui_data[8]
        smaa_corner_rounding: str = gui_data[9]
        cas_enable: bool = gui_data[18]
        cas_sharpness: str = gui_data[19]
        dls_enable: bool = gui_data[20]
        dls_sharpness: str = gui_data[21]
        dls_denoise: str = gui_data[22]
        
        # Get Directory Path
        directory_path: str = os.path.dirname(app_path_in) + "/"
        

        # Determine CAS string
        if cas_enable == True:
            cas_str: str = "cas"
        else:
            cas_str: str = ""

        # Determine DLS string
        if dls_enable == True:
            dls_str: str = "dls"
        else:
            dls_str: str = ""

        # Determine FXAA string
        if fxaa_enable == True:
            fxaa_str: str = "fxaa"
        else:
            fxaa_str: str = ""

        # Determine SMAA string
        if smaa_enable == True:
            smaa_str: str = "smaa"
        else:
            smaa_str: str = ""

        with open(f"{directory_path}{self._vkbasalt_config}", "w+") as vkbasalt_conf_file:
            vkbasalt_conf_file.write("# vkBasalt Configuration File\n")
            vkbasalt_conf_file.write("# Generated by Linux 3D Graphics Settings Manager\n# \n")
            vkbasalt_conf_file.write("# Effects List:\n")
            vkbasalt_conf_file.write(f"effects = {smaa_str}:{fxaa_str}:{dls_str}:{cas_str}\n\n")
            
            # Rationale for effects order
            vkbasalt_conf_file.write("# Effect Order Rationale:\n")
            vkbasalt_conf_file.write("# SMAA is applied first to handle primary anti-aliasing.\n")
            vkbasalt_conf_file.write("# FXAA follows to further smooth edges after SMAA.\n")
            vkbasalt_conf_file.write("# DLS is applied next to enhance image sharpness after AA passes.\n")
            vkbasalt_conf_file.write("# CAS is applied last to provide final sharpening to the image.\n")
            vkbasalt_conf_file.write("# This works in this order despite one or more setttings being disabled.\n# \n")
            
            # Separator
            vkbasalt_conf_file.write("# \n")

            # Write CAS settings
            vkbasalt_conf_file.write("# Contrast Adaptive Sharpening (CAS) Settings\n# \n")
            if cas_enable == True:
                # Write CAS Sharpness selected setting
                vkbasalt_conf_file.write("# CAS Sharpness Amount:\n# \n")
                if cas_sharpness == "Off" or cas_sharpness == "Select Option...":
                    vkbasalt_conf_file.write("# casSharpness = 0.0\n")
                else:
                    vkbasalt_conf_file.write(f"casSharpness = {cas_sharpness}\n")
            elif cas_enable == "Disabled" or cas_enable == "Select Option...":
                vkbasalt_conf_file.write("# casSharpness = 0.0\n")
            
            # Separator
            vkbasalt_conf_file.write("# \n")

            # Write DLS settings
            vkbasalt_conf_file.write("# Denoised Luma Sharpening (DLS) Settings\n# \n")
            if dls_enable == True:
                # Write DLS Sharpness selected setting
                vkbasalt_conf_file.write("# DLS Sharpness Amount:\n# \n")
                if dls_sharpness == "Select Option...":
                    vkbasalt_conf_file.write("# dlsSharpness = 0.0\n")
                else:
                    vkbasalt_conf_file.write(f"dlsSharpness = {dls_sharpness}\n")
                
                # Separator
                vkbasalt_conf_file.write("# \n")

                # Write DLS Denoise selected setting
                vkbasalt_conf_file.write("# DLS Denoise Amount:\n# \n")
                if dls_denoise == "Select Option...":
                    vkbasalt_conf_file.write("# dlsDenoise = 0.0\n")
                else:
                    vkbasalt_conf_file.write(f"dlsDenoise = {dls_denoise}\n")
            elif dls_enable == "Disabled" or dls_enable == "Select Option...":
                vkbasalt_conf_file.write("# dlsSharpness = 0.0\n")
                vkbasalt_conf_file.write("# dlsDenoise = 0.0\n")

            # Separator
            vkbasalt_conf_file.write("# \n")

            # Write FXAA settings
            vkbasalt_conf_file.write("# FXAA Settings\n# \n")
            if fxaa_enable == True:
                # Write FXAA Quality Subpixel selected setting
                vkbasalt_conf_file.write("# FXAA Quality Subpixel:\n# \n")
                if fxaa_quality_subpixel == "Select Option...":
                    vkbasalt_conf_file.write("# fxaaQualitySubpix = 0.00\n")
                else:
                    vkbasalt_conf_file.write(f"fxaaQualitySubpix = {fxaa_quality_subpixel}\n")
                
                # Separator
                vkbasalt_conf_file.write("# \n")

                # Write FXAA Quality Edge selected setting
                vkbasalt_conf_file.write("# FXAA Quality Edge:\n# \n")
                if fxaa_quality_edge == "Select Option...":
                    vkbasalt_conf_file.write("# fxaaQualityEdgeThreshold = disabled\n")
                elif fxaa_quality_edge == "Lowest Quality":
                    vkbasalt_conf_file.write("fxaaQualityEdgeThreshold = 0.333\n")
                elif fxaa_quality_edge == "Low Quality":
                    vkbasalt_conf_file.write("fxaaQualityEdgeThreshold = 0.250\n")
                elif fxaa_quality_edge == "Default":
                    vkbasalt_conf_file.write("fxaaQualityEdgeThreshold = 0.166\n")
                elif fxaa_quality_edge == "High Quality":
                    vkbasalt_conf_file.write("fxaaQualityEdgeThreshold = 0.115\n")
                elif fxaa_quality_edge == "Highest Quality":
                    vkbasalt_conf_file.write("fxaaQualityEdgeThreshold = 0.063\n")
                
                # Separator
                vkbasalt_conf_file.write("# \n")

                # Write FXAA Edge Threshold selected setting
                vkbasalt_conf_file.write("# FXAA Edge Threshold:\n# \n")
                if fxaa_edge_threshold == "Select Option...":
                    vkbasalt_conf_file.write("# fxaaEdgeThreshold = disabled\n")
                elif fxaa_edge_threshold == "Zero":
                    vkbasalt_conf_file.write("fxaaEdgeThreshold = 0.0000\n")
                elif fxaa_edge_threshold == "Visible Limit":
                    vkbasalt_conf_file.write("fxaaEdgeThreshold = 0.0312\n")
                elif fxaa_edge_threshold == "High Quality":
                    vkbasalt_conf_file.write("fxaaEdgeThreshold = 0.0625\n")
                elif fxaa_edge_threshold == "Upper Limit":
                    vkbasalt_conf_file.write("fxaaEdgeThreshold = 0.0833\n")
            elif fxaa_enable == "Disabled" or fxaa_enable == "Select Option...":
                vkbasalt_conf_file.write("# fxaaQualitySubpix = disabled\n")
                vkbasalt_conf_file.write("# fxaaQualityEdgeThreshold = disabled\n")
                vkbasalt_conf_file.write("# fxaaEdgeThreshold = disabled\n")

                # Separator
                vkbasalt_conf_file.write("# \n")

            # Write SMAA settings
            vkbasalt_conf_file.write("# SMAA Settings\n# \n")
            if smaa_enable == True:
                # Write SMAA Edge Detection selected setting
                vkbasalt_conf_file.write("# SMAA Edge Detection Mode:\n# \n")
                if smaa_edge_detection == "Select Option...":
                    vkbasalt_conf_file.write("# smaaEdgeDetection = disabled\n")
                elif smaa_edge_detection == "Color":
                    vkbasalt_conf_file.write("smaaEdgeDetection = color\n")
                elif smaa_edge_detection == "Luma":
                    vkbasalt_conf_file.write("smaaEdgeDetection = luma\n")
                
                # Separator
                vkbasalt_conf_file.write("# \n")

                # Write SMAA Threshold selected setting
                vkbasalt_conf_file.write("# SMAA Threshold:\n# \n")
                if smaa_threshold == "Select Option...":
                    vkbasalt_conf_file.write("# smaaThreshold = disabled\n")
                elif smaa_threshold == "Lowest Quality":
                    vkbasalt_conf_file.write("smaaThreshold = 0.50\n")
                elif smaa_threshold == "Low Quality":
                    vkbasalt_conf_file.write("smaaThreshold = 0.40\n")
                elif smaa_threshold == "Balanced":
                    vkbasalt_conf_file.write("smaaThreshold = 0.25\n")
                elif smaa_threshold == "Quality":
                    vkbasalt_conf_file.write("smaaThreshold = 0.10\n")
                elif smaa_threshold == "Highest Quality":
                    vkbasalt_conf_file.write("smaaThreshold = 0.05\n")
                
                # Separator
                vkbasalt_conf_file.write("# \n")

                # Write SMAA Search Steps selected setting
                vkbasalt_conf_file.write("# SMAA Search Steps:\n# \n")
                if smaa_search_steps == "Select Option...":
                    vkbasalt_conf_file.write("# smaaMaxSearchSteps = disabled\n")
                else:
                    vkbasalt_conf_file.write(f"smaaMaxSearchSteps = {smaa_search_steps.strip("x")}\n")
                
                # Separator
                vkbasalt_conf_file.write("# \n")

                # Write SMAA Search Steps Diagonal selected setting
                vkbasalt_conf_file.write("# SMAA Search Steps Diagonal:\n# \n")
                if smaa_search_steps_diagonal == "Select Option...":
                    vkbasalt_conf_file.write("# smaaMaxSearchStepsDiag = disabled\n")
                else:
                    vkbasalt_conf_file.write(f"smaaMaxSearchStepsDiag = {smaa_search_steps_diagonal.strip("x")}\n")

                # Separator
                vkbasalt_conf_file.write("# \n")

                # Write SMAA Corner Rounding selected setting
                vkbasalt_conf_file.write("# SMAA Corner Rounding:\n# \n")
                if smaa_corner_rounding == "Select Option...":
                    vkbasalt_conf_file.write("# smaaCornerRounding = disabled\n")
                else:
                    vkbasalt_conf_file.write(f"smaaCornerRounding = {smaa_corner_rounding}\n")
            elif smaa_enable == "Disabled" or smaa_enable == "Select Option...":
                vkbasalt_conf_file.write("# smaaEdgeDetection = luma\n")
                vkbasalt_conf_file.write("# smaaThreshold = disabled\n")
                vkbasalt_conf_file.write("# smaaSearchSteps = disabled\n")
                vkbasalt_conf_file.write("# smaaSearchStepsDiagonal = disabled\n")

    def save_conf_dxvk(self,
                       app_path_in: str,
                       settings_list: list) -> None:
        """
        Saves DXVK configuration based on provided settings from dropdowns in settings_panel.py.

        Args:
            app_path_in (str): Path to the application directory.
            settings_list (list): List of settings values from the GUI.
        
        Returns:
            None.

        Raises:
            None.
        
        Example:
            Default usage:
                .. code-block:: python
                >>> conf_handler = AppConfHandler()
                >>> conf_handler.save_conf_dxvk("/path/to/app", settings_list)
        """
        # Unpack settings list
        gui_data: list = settings_list

        anistropic_enable: str = gui_data[10]
        anistropic_level: str = gui_data[11]
        anistropic_level_d3d9: str = gui_data[12]
        lod_enable: str = gui_data[13]
        lod_bias: str = gui_data[14]
        lod_bias_d3d9: str = gui_data[15]
        clamp_negative_lod: str = gui_data[16]
        clamp_negative_lod_d3d9: str = gui_data[17]
        vsync_enable: str = gui_data[23]
        vsync_level: str = gui_data[24]
        vsync_level_d3d9: str = gui_data[25]
        frame_limit_enable: str = gui_data[26]
        frame_limit_level: str = gui_data[27]
        frame_limit_level_d3d9: str = gui_data[28]
        hdr_enable: bool = gui_data[29]
        d3d_level: str = gui_data[30]
        
        # Get Directory Path
        directory_path: str = os.path.dirname(app_path_in) + "/"

        with open(f"{directory_path}{self._dxvk_config}", "w+") as dxvk_conf_file:
            dxvk_conf_file.write("# DXVK Configuration File\n")
            dxvk_conf_file.write("# Generated by Linux 3D Graphics Settings Manager\n# \n")

            # Write Anisotropic Filtering settings
            dxvk_conf_file.write("# Anisotropic Filtering Settings\n# \n")
            if anistropic_enable == "Enable" and anistropic_level != None:
                # Write Anisotropic Level selected setting
                dxvk_conf_file.write("# Anisotropic Filtering Level for D3D10/11:\n# \n")
                if anistropic_level == "Select Option...":
                    dxvk_conf_file.write("# d3d11.samplerAnisotropy = disabled\n")
                else:
                    dxvk_conf_file.write(f"d3d11.samplerAnisotropy = {anistropic_level.strip("x")}\n")
            elif anistropic_enable == "Disable" and anistropic_level == None:
                dxvk_conf_file.write("# Anisotropic Filtering Level for D3D10/11:\n# \n")
                dxvk_conf_file.write("# Disabled\n")
                dxvk_conf_file.write("# d3d11.samplerAnisotropy = disabled\n")

            # Write Anisotropic Filtering settings for D3D9
            if anistropic_enable == "Enable (D3D9)" and anistropic_level_d3d9 != None:
                # Write Anisotropic Level selected setting
                dxvk_conf_file.write("# Anisotropic Filtering Level for D3D9:\n# \n")
                if anistropic_level_d3d9 == "Select Option...":
                    dxvk_conf_file.write("# d3d9.samplerAnisotropy = disabled\n")
                else:
                    dxvk_conf_file.write(f"d3d9.samplerAnisotropy = {anistropic_level_d3d9.strip("x")}\n")
            elif anistropic_enable == "Disable" and anistropic_level_d3d9 == None:
                dxvk_conf_file.write("# Anisotropic Filtering Level for D3D9:\n# \n")
                dxvk_conf_file.write("# Disabled\n")
                dxvk_conf_file.write("# d3d9.samplerAnisotropy = disabled\n")

            # Separator
            dxvk_conf_file.write("# \n")

            # Write LOD settings
            dxvk_conf_file.write("# Level of Detail (LOD) Settings\n# \n")
            if lod_enable == "Enable" and lod_bias != None:
                # Write LOD Bias selected setting
                dxvk_conf_file.write("# LOD Bias for D3D10/11:\n# \n")
                if lod_bias == "Select Option...":
                    dxvk_conf_file.write("# d3d11.samplerLodBias = disabled\n")
                else:
                    dxvk_conf_file.write(f"d3d11.samplerLodBias = {lod_bias}\n")
            elif lod_enable == "Disable" and lod_bias == None:
                dxvk_conf_file.write("# LOD Bias for D3D10/11:\n# \n")
                dxvk_conf_file.write("# Disabled\n")
                dxvk_conf_file.write("# d3d11.samplerLodBias = disabled\n")

            # Write Clamp Negative LOD Bias settings
            dxvk_conf_file.write("# Clamp Negative LOD Bias Settings\n# \n")
            if lod_enable == "Enable" and clamp_negative_lod != None:
                # Write Clamp Negative LOD selected setting
                dxvk_conf_file.write("# Clamp Negative LOD for D3D10/11:\n# \n")
                if clamp_negative_lod == "Select Option...":
                    dxvk_conf_file.write("# d3d11.clampNegativeLodBias = disabled\n")
                elif clamp_negative_lod == "Enabled":
                    dxvk_conf_file.write("d3d11.clampNegativeLodBias = True\n")
                elif clamp_negative_lod == "Disabled":
                    dxvk_conf_file.write("d3d11.clampNegativeLodBias = False\n")
            elif lod_enable == "Disable" and clamp_negative_lod == None:
                dxvk_conf_file.write("# Clamp Negative LOD for D3D10/11:\n# \n")
                dxvk_conf_file.write("# Disabled\n")
                dxvk_conf_file.write("# d3d11.clampNegativeLodBias = disabled\n")

            # Write LOD settings for D3D9
            if lod_enable == "Enable (D3D9)" and lod_bias_d3d9 != None:
                # Write LOD Bias selected setting
                dxvk_conf_file.write("# LOD Bias for D3D9:\n# \n")
                if lod_bias_d3d9 == "Select Option...":
                    dxvk_conf_file.write("# d3d9.samplerLodBias = disabled\n")
                else:
                    dxvk_conf_file.write(f"d3d9.samplerLodBias = {lod_bias_d3d9}\n")
            elif lod_enable == "Disable" and lod_bias_d3d9 == None:
                dxvk_conf_file.write("# LOD Bias for D3D9:\n# \n")
                dxvk_conf_file.write("# Disabled\n")
                dxvk_conf_file.write("# d3d9.samplerLodBias = disabled\n")

            # Write Clamp Negative LOD settings for D3D9
            if lod_enable == "Enable (D3D9)" and clamp_negative_lod_d3d9 != None:
                # Write Clamp Negative LOD selected setting
                dxvk_conf_file.write("# Clamp Negative LOD for D3D9:\n# \n")
                if clamp_negative_lod_d3d9 == "Select Option...":
                    dxvk_conf_file.write("# d3d9.clampNegativeLodBias = disabled\n")
                elif clamp_negative_lod_d3d9 == "Enabled":
                    dxvk_conf_file.write("d3d9.clampNegativeLodBias = True\n")
                elif clamp_negative_lod_d3d9 == "Disabled":
                    dxvk_conf_file.write("d3d9.clampNegativeLodBias = False\n")
            elif lod_enable == "Disable" and clamp_negative_lod_d3d9 == None:
                dxvk_conf_file.write("# Clamp Negative LOD for D3D9:\n# \n")
                dxvk_conf_file.write("# Disabled\n")
                dxvk_conf_file.write("# d3d9.clampNegativeLodBias = disabled\n")

            # Separator
            dxvk_conf_file.write("# \n")

            # Write VSync settings
            if vsync_enable == "Enable" and vsync_level != None:
                # Write VSync selected setting
                dxvk_conf_file.write("# VSync for D3D10/11:\n# \n")
                if vsync_level == "Select Option...":
                    dxvk_conf_file.write("# dxgi.syncInterval = -1\n")
                elif vsync_level == "Off":
                    dxvk_conf_file.write("dxgi.syncInterval = 0\n")
                else:
                    dxvk_conf_file.write(f"dxgi.syncInterval = {vsync_level.strip(" Frames")}\n")
            elif vsync_enable == "Disable" and vsync_level == None:
                dxvk_conf_file.write("# VSync for D3D10/11:\n# \n")
                dxvk_conf_file.write("# Disabled\n")
                dxvk_conf_file.write("# dxgi.syncInterval = -1\n")
            
            # Write Frame Limit Settings
            if frame_limit_enable == "Enable" and frame_limit_level != None:
                # Write Frame limit selected setting
                dxvk_conf_file.write("# \n# Frame Limit for D3D10/11:\n# \n")
                if frame_limit_level == "Select Option...":
                    dxvk_conf_file.write("# dxgi.maxFrameRate = 0\n")
                else:
                    dxvk_conf_file.write(f"dxgi.maxFrameRate = {frame_limit_enable}\n")
            elif frame_limit_enable == "Disable" and frame_limit_enable == None:
                dxvk_conf_file.write("# Frame Limit for D3D10/11:\n# \n")
                dxvk_conf_file.write("# Disabled\n")
                dxvk_conf_file.write("# dxgi.maxFrameRate = 0\n")

            # Write VSync settings for D3D9
            if vsync_enable == "Enable (D3D9)" and vsync_level_d3d9 != None:
                # Write VSync selected setting
                dxvk_conf_file.write("# VSync for D3D9:\n# \n")
                if vsync_level_d3d9 == "Select Option...":
                    dxvk_conf_file.write("# d3d9.presentInterval = -1\n")
                elif vsync_level_d3d9 == "Off":
                    dxvk_conf_file.write("d3d9.presentInterval = 0\n")
                else:
                    dxvk_conf_file.write(f"d3d9.presentInterval = {vsync_level_d3d9.strip(" Frames")}\n")
            elif vsync_enable == ("Disable") and vsync_level_d3d9 == None:
                dxvk_conf_file.write("# VSync for D3D9:\n# \n")
                dxvk_conf_file.write("# Disabled\n")
                dxvk_conf_file.write("# d3d9.presentInterval = -1")

            # Write Frame Limit settings for D3D9
            if frame_limit_enable == "Enable (D3D9)" and frame_limit_level_d3d9 != None:
                # Write Frame Limit selected setting
                dxvk_conf_file.write("# Frame Limit for D3D9:\n# \n")
                if frame_limit_level_d3d9 == "Select Opiton...":
                    dxvk_conf_file.write("# d3d9.maxFrameRate = 0\n")
                else:
                    dxvk_conf_file.write(f"d3d9.maxFrameRate = {frame_limit_level_d3d9}\n")
            elif frame_limit_enable == "Disable" and frame_limit_level_d3d9 == None:
                dxvk_conf_file.write("# Frame Limit for D3D9:\n")
                dxvk_conf_file.write("# Disabled\n")
                dxvk_conf_file.write("# d3d9.maxFrameRate = 0\n")

            # Write Tear Free setting to Auto
            dxvk_conf_file.write("dxvk.tearFree = Auto\n")

            # Separator
            dxvk_conf_file.write("# \n")

            # Write HDR setting
            dxvk_conf_file.write("# HDR Setting:\n")
            if hdr_enable == True:
                dxvk_conf_file.write("dxgi.enableHDR = True\n")
            elif hdr_enable == False:
                dxvk_conf_file.write("dxgi.enableHDR = False\n")
            elif hdr_enable == None:
                dxvk_conf_file.write("# Disabled\n")
                dxvk_conf_file.write("# dxgi.enableHDR = disabled\n")

            # Separator
            dxvk_conf_file.write("# \n")

            # Write D3D Level setting
            dxvk_conf_file.write("# D3D Feature Level:\n# \n")
            if d3d_level != None:
                # Write D3D Level selected setting
                if d3d_level == "Direct X 9.1":
                    dxvk_conf_file.write("d3d11.maxFeatureLevel = 9_1\n")
                elif d3d_level == "Direct X 9.2":
                    dxvk_conf_file.write("d3d11.maxFeatureLevel = 9_2\n")
                elif d3d_level == "Direct X 9.3":
                    dxvk_conf_file.write("d3d11.maxfeatureLevel = 9_3\n")
                elif d3d_level == "Direct X 10.0":
                    dxvk_conf_file.write("d3d11.maxFeatureLevel = 10_0\n")
                elif d3d_level == "Direct X 10.1":
                    dxvk_conf_file.write("d3d11.maxFeatureLevel = 10_1\n")
                elif d3d_level == "Direct X 11.0":
                    dxvk_conf_file.write("d3d11.maxFeatureLevel = 11_0\n")
                elif d3d_level == "Direct X 11.1":
                    dxvk_conf_file.write("d3d11.maxFeatureLevel = 11_1\n")
                elif d3d_level == "Direct X 12.0":
                    dxvk_conf_file.write("d3d11.maxFeatureLevel = 12_0\n")
                elif d3d_level == "Direct X 12.1":
                    dxvk_conf_file.write("d3d11.maxFeatureLevel = 12_1\n")
            else:
                dxvk_conf_file.write("# Disabled")
                dxvk_conf_file.write("# d3d11.maxFeatureLevel = disabled")
